apiVersion: v1
kind: Pod
metadata:
  name: test-log-pod
spec:
  containers:
  - name: test-log-pod
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do echo "Test Log SEZER $i"; i=$((i+1)); sleep 1; done']
